### ISSUE TITLE
out of memory on large dumps

### ISSUE THREAD

**Issue by nrobert13** [GoogleCloudPlatform/cloudsql-import#14]
I'm trying to import a 200G file on a machine with 4G RAM, and getting :
I guess it tries to read the whole file into mem.

```
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x66e4fb, 0x16)
        /usr/lib/go-1.11/src/runtime/panic.go:608 +0x72
runtime.sysMap(0xc080000000, 0x80000000, 0x8308d8)
        /usr/lib/go-1.11/src/runtime/mem_linux.go:156 +0xc7
runtime.(*mheap).sysAlloc(0x8176e0, 0x80000000, 0x0, 0x7fff950eb110)
        /usr/lib/go-1.11/src/runtime/malloc.go:619 +0x1c7
runtime.(*mheap).grow(0x8176e0, 0x40000, 0x0)
        /usr/lib/go-1.11/src/runtime/mheap.go:920 +0x42
runtime.(*mheap).allocSpanLocked(0x8176e0, 0x40000, 0x8308e8, 0x1100000012)
        /usr/lib/go-1.11/src/runtime/mheap.go:848 +0x337
runtime.(*mheap).alloc_m(0x8176e0, 0x40000, 0xffffffffffff0101, 0x7fff950eb1f0)
        /usr/lib/go-1.11/src/runtime/mheap.go:692 +0x119
runtime.(*mheap).alloc.func1()
        /usr/lib/go-1.11/src/runtime/mheap.go:759 +0x4c
runtime.(*mheap).alloc(0x8176e0, 0x40000, 0x7fff95010101, 0x434c3f)
        /usr/lib/go-1.11/src/runtime/mheap.go:758 +0x8a
runtime.largeAlloc(0x80000000, 0xc000020101, 0xc000000300)
        /usr/lib/go-1.11/src/runtime/malloc.go:1019 +0x97
runtime.mallocgc.func1()
        /usr/lib/go-1.11/src/runtime/malloc.go:914 +0x46
runtime.systemstack(0x4554a9)
        /usr/lib/go-1.11/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
        /usr/lib/go-1.11/src/runtime/proc.go:1229

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/lib/go-1.11/src/runtime/asm_amd64.s:311 fp=0xc000045a08 sp=0xc000045a00 pc=0x4555a0
runtime.mallocgc(0x80000000, 0x61b6a0, 0x1, 0xc03ffb4000)
        /usr/lib/go-1.11/src/runtime/malloc.go:913 +0x896 fp=0xc000045aa8 sp=0xc000045a08 pc=0x40d4a6
runtime.makeslice(0x61b6a0, 0x80000000, 0x80000000, 0x4000000a, 0xffffffffffffffff, 0x31ec9ce922)
        /usr/lib/go-1.11/src/runtime/slice.go:70 +0x77 fp=0xc000045ad8 sp=0xc000045aa8 pc=0x440ee7
main.main()
        /home/robert.nemeti/go/src/github.com/GoogleCloudPlatform/cloudsql-import/main.go:269 +0x9b6 fp=0xc000045f98 sp=0xc000045ad8 pc=0x5f5b76
runtime.main()
        /usr/lib/go-1.11/src/runtime/proc.go:201 +0x207 fp=0xc000045fe0 sp=0xc000045f98 pc=0x42d477
runtime.goexit()
        /usr/lib/go-1.11/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000045fe8 sp=0xc000045fe0 pc=0x457681

goroutine 5 [select]:
database/sql.(*DB).connectionOpener(0xc00009e000, 0x6a7140, 0xc000052300)
        /usr/lib/go-1.11/src/database/sql/sql.go:1001 +0xe8
created by database/sql.OpenDB
        /usr/lib/go-1.11/src/database/sql/sql.go:671 +0x15d

goroutine 6 [select]:
database/sql.(*DB).connectionResetter(0xc00009e000, 0x6a7140, 0xc000052300)
        /usr/lib/go-1.11/src/database/sql/sql.go:1014 +0xfb
created by database/sql.OpenDB
        /usr/lib/go-1.11/src/database/sql/sql.go:672 +0x193

```

**Comment by nrobert13** [comment]
@kurtisvg , what would be the solution here?
